jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i
        timeout-minutes: 6

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        timeout-minutes: 10

      - name: Make data folder
        run: mkdir -p data

      - name: Scrape BB
        run: node scrape/prca.js BB 2025 > data/BB.json
        timeout-minutes: 6

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: |
            data/debug/**
            data/BB.json
